# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393



GPC_yi_parallel <- function(nn, data, theta_boot, data_boot, alpha, M_samp, B_resamp) {
    .Call(`GPC_GPC_yi_parallel`,  nn, data, theta_boot, data_boot, alpha, M_samp, B_resamp)
}

rcpp_parallel_yi <- function(nn, data, thetaboot, bootmean0, bootmean1, databoot, alpha, M_samp, B_resamp, w){
    .Call(`GPC_rcpp_parallel_yi`,  nn, data, thetaboot, bootmean0, bootmean1, databoot, alpha, M_samp, B_resamp, w)   
}

GibbsMCMC2 <- function(nn, data, thetaboot, bootmean0, bootmean1, alpha, M_samp, w){
    .Call(`GPC_GibbsMCMC2`, nn, data, thetaboot, bootmean0, bootmean1, alpha, M_samp, w)    
}

